### ISSUE TITLE
[Bug] Can't generate launcher with Bridge listener

### ISSUE THREAD

**Issue by decardcain603** [cobbr/Covenant#142]
**Feature Request or Bug**
Bug

**Describe the feature request or bug**
After setting up a bridge listener with TCPBridgeProfile, it is impossible to generate a launcher.

**To Reproduce**
1. Go to Listeners->Create->BridgeListener
2. Leave values on default (Bind: 7444, connect: 7445 etc)
3. Select TCPBridgeProfile as the requested BridgeProfile
4. Goto Launchers->PowerShell
5. Select the Listener you've just created. Template is automatically set as GruntBridge
6. Click 'Generate'
The 'Launcher' command line is not being generated.

**Expected behavior**
Launcher command line is being generated

**Covenant Server Information:**
 - OS: Ubuntu 18.04
 - Docker or Native: Native

**Browser Information:**
 - Browser Chrome 
 - Version 71.0.3578.98

**Target Information (System that implant is running on):**
N/A

**Additional context**
N/A

**Comment by cobbr** [comment]
Thanks for heads up @decardcain603. Implants that communicate over non-http profiles had not really been supported or tested on any launcher besides the BinaryLauncher, but it turned out that this was very simple and easy to do.

This should be supported in 85ba494ae4a5f429798466e0ad20370e03b815c2 in dev branch, will be merged to master soon.

Thanks again @decardcain603! 🙂
