### ISSUE TITLE
[Feature Request] SMB Listener feature

### ISSUE THREAD

**Issue by Acebond** [cobbr/Covenant#21]
An SMB listener would be useful in environment with subnetting, VLANs, or machine without Internet access. 

I figured this could be implemented with a new listener type (SmbListener), and Launchers could then be generated with the SMB listener payload. A link command would need to be implemented within Grunt to connect and then proxy the traffic.

I'm diving into the source code to see how difficult this would be to implement. I make no promises and will definitely need help.

**Comment by cobbr** [comment]
Hey @Acebond. I agree that this would be very useful :) So much so that I've actually already been actively developing this, and hopefully will open source it in the near future.

I have formatted it a bit different than you have described. I think a true egress SMB listener could be interesting as well. If you are interested in implementing that, I'm definitely willing to provide help/ideas as you go!

**Comment by Acebond** [comment]
That's awesome. I've really jumped in the deep end by picking this project to learn C# and am still trying to wrap my head around the Covenant code base. I'll ping you on Twitter as I'm curious about your development setup and how you debug a Grunt.

**Comment by cobbr** [comment]
Yeah feel free to reach out on twitter or slack. The codebase is a bit more complex than it probably needs to be, so hopefully can make it less so.

**Comment by cobbr** [comment]
Added in 1d1daaad77786a9eb7fb8c7be0fc56f75b653421!
