### ISSUE TITLE
[Feature Request] Offline/Isolated C2

### ISSUE THREAD

**Issue by cetaSYN** [cobbr/Covenant#258]
**Feature Request**
Ability to easily pre-download NuGet resources for using Covenant C2 in an environment where internet access is unavailable

**Describe the feature request or bug**
A run-flag to pre-download any resources that later would usually require an internet connection or a support script to populate such resources

**Additional context**
When using Covenant on an internet-isolated range, it doesn't run because NuGet fails to pull resources.
It's easy enough to pre-run it prior to the disconnect, but now I'm finding that generating a Brute also attempts and fails with NuGet.
Probably not super common, but it would be awesome if there was a way to build a Covenant instance that came with everything already in place.

**Comment by mubix** [comment]
I have run into this scenario as well. Thanks for making an issue for it.

**Comment by johanssontobbe** [comment]
I could use this feature as well.

**Comment by cobbr** [comment]
@cetaSYN/anyone

I'm pretty confident that this is already possible. Just run `dotnet build` when you have Internet connection to build the project, take away Internet access, and then do `dotnet ./bin/Debug/net5.0/Covenant.dll` to run offline w/ no build.

(This is assuming dev branch using net5.0, will be a different path if you are still on netcore3.1)

I'll try to verify, but let me know if anyone is able to test.

**Comment by cobbr** [comment]
Going to close this for now. If I'm wrong and this is not possible via the method described, just let me know and we can re-open.

**Comment by bitBossBBQ** [comment]
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x#global-packages-folder

The documentation for **dotnet restore** states that once downloaded, nuget packages are saved using the --packages option.  If not specified, the packages are stored in ~/.nuget/packages.  In order to get the dependencies for offline use you can use **dotnet restore** from the same directory you'd run **dotnet run** from, then you should have the required packages saved in the path mentioned above.  If you need to "sneakernet" the packages, just download that directory and transfer it to the same directory in the offline system.  The referenced documentation is provided in the link above.  Hopefully this helps.
@cobbr This could be implemented in a future "build" script packed with the repo.
