### ISSUE TITLE
Bypass UAC does not provide elevated shell

### ISSUE THREAD

**Issue by whitefi** [cobbr/Covenant#40]
Hey, the bypass uac command and bypass uac grunt modules do not appear to give an elevated shell.

The following image shows 3 grunts. 

1) Manual_UAC_ByPass - used powershell in an elevated cmd by manually right clicking and running cmd.exe as an administrator

2) GruntByPAss - used "BypassUACGrunt PowerShell" from the medium integrity grunt

3) 20f748d281 - grunt used to get a high integrity shell (GruntByPAss)

![image](https://user-images.githubusercontent.com/24624058/63435718-50caa980-c41f-11e9-9500-ff0052ae0249.png)

Safteykatz etc fails to run on a high integrity grunt when using BypassUACGrunt or BypassUACCommand.

When running whoami /priv we can see that it fails to properly elevate the shell and thus unable to impersonate SYSTEM / Run mimikatz etc.

Manual_UAC_ByPass:

![image](https://user-images.githubusercontent.com/24624058/63436827-51643f80-c421-11e9-909c-84709d7e2ee0.png)

GruntByPAss
![image](https://user-images.githubusercontent.com/24624058/63436859-604af200-c421-11e9-8eec-a1303f5d1ad3.png)

**Comment by rasta-mouse** [comment]
What version of Windows are you running against?  I'm pretty sure Covenant uses SharpSploits [Token Class](https://sharpsploit.cobbr.io/api/SharpSploit.Credentials.Tokens.html#SharpSploit_Credentials_Tokens_BypassUAC_System_String_System_String_System_String_System_Int32_) which uses Token Duplication.  This was fixed in the 1809 release.

**Comment by whitefi** [comment]
10.0.14393 Build 14393

**Comment by cobbr** [comment]
@whitefi There's a lot to consider with this.

First, @rasta-mouse is correct that 1809+ the BypassUAC tasks will not work, since the token duplication method has been patched.

But, to me it looks like you successfully used the BypassUAC modules to get a new Grunt with a High Integrity session.

In addition to being High vs Medium integrity, a token has a set of enabled privileges. It looks like you are in an odd situation where you have high integrity token that does not have the appropriate privileges for whatever task you are trying to accomplish.

It would be useful in this situation to have a "getprivs" type of builtin task. Unfortunately, I don't anything like that builtin as a task. However, SharpSploit does have this ability, and can be utilized with the `SharpShell` command: https://github.com/cobbr/SharpSploit/blob/master/SharpSploit/Credentials/Tokens.cs#L511

Other 3rd-party tools may be able to accomplish this as well, you might look into Tokenvator.

**Comment by kjblack** [comment]
Thanks, will carry on working on alternatives for newer builds

**Comment by rasta-mouse** [comment]
Those privs look normal to me after a Token Duplication UAC Bypass.  Raffi talks about it here
https://www.youtube.com/watch?v=kwnTf253pgI

**Comment by whitefi** [comment]
Perfect. Thanks for the YouTube link.
Clears alot about about this technique, not all is lost 😎

**Comment by cobbr** [comment]
This is great info to have, thanks for sharing @rasta-mouse

**Comment by cobbr** [comment]
Closing for now. Let me know if you still have more issues @whitefi
